package enigma_test

import (
	"testing"

	"github.com/windhooked/yaee/src/enigma"
)

/*
Plaintext:

SSDCHEFFUNFXUUUFLOTTXXEINSKKTTTFFFEINSACHTMITZWOSTELLKARTENAUSRUESTUNGSKAGERRAKUNDNORWEGENMITHAFENPLAENENUNDEINSEXEMPLARLFDXBEFXBBBDDDUUUOOOPPPNRXSIEBENVOMZWOVIERXVIERXVIERFUNFXSOFORTNEUSTADTINMARSCHSETZENXZWOKKTTTFFFEINBNEUNVORLPEUFIGKIELBLEIBENXDHEIKKBESTARTEHXNGERBETENXXFXDXUUUAUSBXKF

Interpretation (preliminary):

SEHR SEHR DRINGEND [An] Chef 5. U-Flott:
1) Torpedofangboot 18 mit 2 Stellkarten Ausrüstung Skagerrak und Norwegen mit Hafenplänen und 1 Exemplar laufende Befehl B.d.U. Op. Nr. 7 vom 24.4.45. sofort Neustadt in Marsch setzen.
2) Torpedofangboot 19 vorläufig Kiel bleiben.
3) Bestätigung erbeten.
*/

func TestDecode(t *testing.T) {

	enigma.Format("FRFQQOWAFIFFAZZMPPAPMWFAYFGVFQAOZFPAWAPLWACATCOWAVQAOFJATWAJQAWOEDJAFATFERAVCJMAGJQAAAFEIOYMLIGAVLCTZIWOQOTAPIPTEBAOWQWAEGCGDBTEAVBALMAAAAZIIQW")
}
