package enigma

/*
https://de.wikipedia.org/wiki/Enigma-Walzen#Walzenverdrahtung

ETW	ABCDEFGHIJKLMNOPQRSTUVWXYZ		M4
UKW Bruno	ENKQAUYWJICOPBLMDXZVFTHRGS	1. Februar 1942	M4
UKW Cäsar	RDOBJNTKVEHMLFCWZAXGYIPSUQ	1. Juli 1943	M4
Beta	LEYJVCNIXWPBQMDRTAKZGFUHOS	1. Februar 1942	M4
Gamma	FSOKANUERHMBTIYCWLQPZXVGJD	1. Juli 1943	M4

ETW = Input Rotor
UKW = Reflector

*/
const (
	UKW_A     = "EJMZALYXVBWFCRQUONTSPIKHGD"
	UKW_B     = "YRUHQSLDPXNGOKMIEBFZCWVJAT" // 	2. November 193"
	UKW_C     = "FVPJIAOYEDRZXWGCTKUQSBNMHL" // 	1940"
	UKW_Bruno = "ENKQAUYWJICOPBLMDXZVFTHRGS"
	UKW_Casar = "RDOBJNTKVEHMLFCWZAXGYIPSUQ"
)

type (
	UKW struct {
		*W
	}
)
